import type { Book } from "./types"

export const booksData: Book[] = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Classic",
    description: "A classic novel of the Jazz Age that explores themes of wealth, love, and the American Dream.",
    coverUrl: "/great-gatsby-book-cover.png",
    pdfUrl: "https://www.gutenberg.org/files/64317/64317-h/64317-h.htm",
    rating: 4.5,
    pages: 180,
  },
  {
    id: "2",
    title: "1984",
    author: "George Orwell",
    category: "Science Fiction",
    description: "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.",
    coverUrl: "/1984-orwell-book-cover.jpg",
    pdfUrl: "https://www.gutenberg.org/ebooks/61234",
    rating: 4.8,
    pages: 328,
  },
  {
    id: "3",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "Romance",
    description: "A romantic novel of manners that satirizes the British landed gentry at the end of the 18th century.",
    coverUrl: "/pride-prejudice-book-cover.jpg",
    pdfUrl: "https://www.gutenberg.org/ebooks/1342",
    rating: 4.6,
    pages: 432,
  },
  {
    id: "4",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Classic",
    description:
      "A gripping, heart-wrenching, and wholly remarkable tale of coming-of-age in a South poisoned by virulent prejudice.",
    coverUrl: "/to-kill-mockingbird-book-cover.jpg",
    pdfUrl: "https://www.gutenberg.org/ebooks/12345",
    rating: 4.7,
    pages: 324,
  },
  {
    id: "5",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "Classic",
    description: "A story about teenage rebellion and alienation that has become a classic of American literature.",
    coverUrl: "/catcher-in-rye-book-cover.jpg",
    pdfUrl: "https://www.gutenberg.org/ebooks/54321",
    rating: 4.3,
    pages: 277,
  },
  {
    id: "6",
    title: "Brave New World",
    author: "Aldous Huxley",
    category: "Science Fiction",
    description:
      "A dystopian novel set in a futuristic World State of genetically modified citizens and an intelligence-based social hierarchy.",
    coverUrl: "/brave-new-world-book-cover.jpg",
    pdfUrl: "https://www.gutenberg.org/ebooks/13579",
    rating: 4.4,
    pages: 311,
  },
  {
    id: "7",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    category: "Fantasy",
    description:
      "A fantasy novel about the journey of home-loving Bilbo Baggins, the hobbit, to win a share of treasure guarded by a dragon.",
    coverUrl: "/hobbit-book-cover.png",
    pdfUrl: "https://www.gutenberg.org/ebooks/24680",
    rating: 4.9,
    pages: 310,
  },
  {
    id: "8",
    title: "Moby-Dick",
    author: "Herman Melville",
    category: "Adventure",
    description: "The narrative of Captain Ahab's obsessive quest to hunt the white whale Moby Dick.",
    coverUrl: "/moby-dick-book-cover.png",
    pdfUrl: "https://www.gutenberg.org/ebooks/2701",
    rating: 4.2,
    pages: 635,
  },
]
